name: http_cache_client
description: HTTP cache client with multiple stores respecting HTTP directives (or not).
version: 1.0.4
repository: https://github.com/llfbandit/dart_http_cache
issue_tracker: https://github.com/llfbandit/dart_http_cache/issues

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  # https://pub.dev/packages/http
  http: ^1.2.0
  http_cache_core: ^1.1.3

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^5.0.0
  # https://pub.dev/packages/test
  test: ^1.24.4
