name: http_cache_isar_store
description: A DB cache store agnostic HTTP client implementation with Isar.
version: 3.0.0-dev.1
repository: https://github.com/llfbandit/dart_http_cache
issue_tracker: https://github.com/llfbandit/dart_http_cache/issues

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  http_cache_core: ^1.1.3

  # https://pub.dev/packages/isar_community
  isar_community: ^3.3.0-dev.3
  # https://pub.dev/packages/isar_community_flutter_libs
  isar_community_flutter_libs: ^3.3.0-dev.3

dev_dependencies:
  isar_community_generator: ^3.3.0-dev.3
  build_runner: any

  # https://pub.dev/packages/lints
  lints: ^5.0.0
  # https://pub.dev/packages/test
  test: ^1.24.4

  http_cache_store_tester: ^1.0.0

